server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres }
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
  application:
    name: ordersync-soap

quartz:
  job:
    process-pending-orders:
      interval-in-seconds: 60
  properties:
    org:
      quartz:
        scheduler:
          instanceName: OrderSyncScheduler
          instanceId: AUTO
        jobStore:
          class: org.quartz.simpl.RAMJobStore